name: Check Pull Request
permissions:
  contents: read
on: [ pull_request, workflow_dispatch ]
jobs:
  check-lib:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew check
        working-directory: ./lib
  check-demo:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew check
        working-directory: ./demo
