name: Check Pull Request (Demo)
permissions:
  contents: read
on:
  pull_request:
    paths:
      - 'demo/**'
  workflow_dispatch:
jobs:
  check:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: |
            demo/**/*.gradle*
            demo/**/gradle-wrapper.properties
            demo/gradle/*.versions.toml
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('demo/**/*.gradle*', 'demo/gradle/*.versions.toml') }}
          restore-keys: ${{ runner.os }}-konan
      - run: ./gradlew check
        working-directory: ./demo
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
