name: Check Pull Request (Demo)
permissions:
  contents: read
on:
  pull_request:
    paths:
      - 'demo/**'
  workflow_dispatch:
jobs:
  check:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew check
        working-directory: ./demo
